name: vault-github-token
description: Create  pipelines access to AWS resources using Workload Identity Federation
author: https://github.com/elastic
public: true
requirements:
  - bash
  - buildkite-agent
configuration:
  properties:
    duration:
      type: number
    aws-account-id:
      type: number
  additionalProperties: false
