name: vault-github-token
description: Create a GITHUB_TOKEN environment variable from VAULT_GITHUB_TOKEN.
author: https://github.com/elastic
public: true
requirements:
  - bash
  - buildkite-agent
configuration:
  additionalProperties: false
