#!/usr/bin/env bash

set -euo pipefail

GITHUB_TOKEN=$VAULT_GITHUB_TOKEN
echo "${VAULT_GITHUB_TOKEN}" | buildkite-agent redactor add || echo "WARNING: Failed to add token to Buildkite redactor. The token may appear in logs." >&2
export GITHUB_TOKEN

if [[ "${BUILDKITE_PLUGIN_VAULT_GITHUB_TOKEN_EXPORT_TF_VAR_GITHUB_TOKEN:-false}" == "true" ]]; then
  TF_VAR_github_token="${GITHUB_TOKEN}"
  export TF_VAR_github_token
fi

if [[ "${BUILDKITE_PLUGIN_VAULT_GITHUB_TOKEN_CONFIGURE_GIT_USER:-false}" == "true" ]]; then
  git config user.email "elastic-ci[bot]@users.noreply.github.com"
  git config user.name "elastic-ci[bot]"
fi