name: ci

on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make test

  plugin-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make plugin-lint
